import type { MealSearchRequest, MealSearchResponse } from '@/types/meal-optimizer-types';

export function generateMockMealResponse(request: MealSearchRequest): MealSearchResponse {
  return {
    resolvedAddress: request.address || 'Tingvej 4A, 2300 København S',
    search: request,
    candidates: [
      {
        candidateId: 'mock-1',
        recipeTemplateId: 'minced-beef-broccoli',
        recipeName: 'Hakket oksekød & Broccoli',
        servingsPerBatch: 3,
        basketCostDkk: 60,
        recipeCostDkk: 48,
        pricePerMealDkk: 16,
        storesUsed: [{ storeId: 'netto', chainId: 'netto', storeName: 'Netto', distanceMeters: 650 }],
        interStoreDistanceMeters: null,
        walkingDistanceMeters: 650,
        chosenIngredients: [
          { slotKey: 'meat', ingredientFamilyId: 'minced-beef', ingredientFamilyName: 'Hakket oksekød', requiredQuantity: { value: 300, unit: 'g' } },
          { slotKey: 'vegetable', ingredientFamilyId: 'broccoli', ingredientFamilyName: 'Broccoli', requiredQuantity: { value: 500, unit: 'g' } },
        ],
        basketLines: [
          {
            ingredientFamilyId: 'minced-beef', ingredientFamilyName: 'Hakket oksekød',
            productName: 'Hakket oksekød 8-12%', storeId: 'netto', storeName: 'Netto',
            packageQuantity: 400, packageUnit: 'g', packageBaseAmount: 400,
            requiredAmountForRecipe: 300, requiredAmountUnit: 'g',
            packagePriceDkk: 35, apportionedCostDkk: 26.25, leftoverAmount: 100, leftoverUnit: 'g',
          },
          {
            ingredientFamilyId: 'broccoli', ingredientFamilyName: 'Broccoli',
            productName: 'Broccoli buketter', storeId: 'netto', storeName: 'Netto',
            packageQuantity: 500, packageUnit: 'g', packageBaseAmount: 500,
            requiredAmountForRecipe: 500, requiredAmountUnit: 'g',
            packagePriceDkk: 25, apportionedCostDkk: 25, leftoverAmount: 0, leftoverUnit: 'g',
          },
        ],
        sauceType: 'cream',
        pantryItems: [{ displayName: 'Pasta' }, { displayName: 'Smør' }, { displayName: 'Hvidløg' }, { displayName: 'Fløde' }],
      },
      {
        candidateId: 'mock-2',
        recipeTemplateId: 'minced-pork-white-cabbage',
        recipeName: 'Hakket svinekød & Hvidkål',
        servingsPerBatch: 4,
        basketCostDkk: 45,
        recipeCostDkk: 38,
        pricePerMealDkk: 9.5,
        storesUsed: [{ storeId: 'lidl', chainId: 'lidl', storeName: 'Lidl', distanceMeters: 900 }],
        interStoreDistanceMeters: null,
        walkingDistanceMeters: 900,
        chosenIngredients: [
          { slotKey: 'meat', ingredientFamilyId: 'minced-pork', ingredientFamilyName: 'Hakket svinekød', requiredQuantity: { value: 300, unit: 'g' } },
          { slotKey: 'vegetable', ingredientFamilyId: 'white-cabbage', ingredientFamilyName: 'Hvidkål', requiredQuantity: { value: 500, unit: 'g' } },
        ],
        basketLines: [
          {
            ingredientFamilyId: 'minced-pork', ingredientFamilyName: 'Hakket svinekød',
            productName: 'Hakket svinekød 8-12%', storeId: 'lidl', storeName: 'Lidl',
            packageQuantity: 500, packageUnit: 'g', packageBaseAmount: 500,
            requiredAmountForRecipe: 300, requiredAmountUnit: 'g',
            packagePriceDkk: 30, apportionedCostDkk: 18, leftoverAmount: 200, leftoverUnit: 'g',
          },
          {
            ingredientFamilyId: 'white-cabbage', ingredientFamilyName: 'Hvidkål',
            productName: 'Hvidkål', storeId: 'lidl', storeName: 'Lidl',
            packageQuantity: 1000, packageUnit: 'g', packageBaseAmount: 1000,
            requiredAmountForRecipe: 500, requiredAmountUnit: 'g',
            packagePriceDkk: 15, apportionedCostDkk: 7.5, leftoverAmount: 500, leftoverUnit: 'g',
          },
        ],
        sauceType: 'asian',
        pantryItems: [{ displayName: 'Ris' }, { displayName: 'Soja' }, { displayName: 'Honning' }, { displayName: 'Ingefær' }],
      },
      {
        candidateId: 'mock-3',
        recipeTemplateId: 'minced-beef-white-cabbage',
        recipeName: 'Hakket oksekød & Hvidkål',
        servingsPerBatch: 3,
        basketCostDkk: 50,
        recipeCostDkk: 39,
        pricePerMealDkk: 13,
        storesUsed: [{ storeId: 'lidl', chainId: 'lidl', storeName: 'Lidl', distanceMeters: 900 }],
        interStoreDistanceMeters: null,
        walkingDistanceMeters: 900,
        chosenIngredients: [
          { slotKey: 'meat', ingredientFamilyId: 'minced-beef', ingredientFamilyName: 'Hakket oksekød', requiredQuantity: { value: 300, unit: 'g' } },
          { slotKey: 'vegetable', ingredientFamilyId: 'white-cabbage', ingredientFamilyName: 'Hvidkål', requiredQuantity: { value: 500, unit: 'g' } },
        ],
        basketLines: [
          {
            ingredientFamilyId: 'minced-beef', ingredientFamilyName: 'Hakket oksekød',
            productName: 'Hakket oksekød 8-12%', storeId: 'lidl', storeName: 'Lidl',
            packageQuantity: 400, packageUnit: 'g', packageBaseAmount: 400,
            requiredAmountForRecipe: 300, requiredAmountUnit: 'g',
            packagePriceDkk: 35, apportionedCostDkk: 26.25, leftoverAmount: 100, leftoverUnit: 'g',
          },
          {
            ingredientFamilyId: 'white-cabbage', ingredientFamilyName: 'Hvidkål',
            productName: 'Hvidkål', storeId: 'lidl', storeName: 'Lidl',
            packageQuantity: 1000, packageUnit: 'g', packageBaseAmount: 1000,
            requiredAmountForRecipe: 500, requiredAmountUnit: 'g',
            packagePriceDkk: 15, apportionedCostDkk: 7.5, leftoverAmount: 500, leftoverUnit: 'g',
          },
        ],
        sauceType: 'tomato',
        pantryItems: [{ displayName: 'Pasta' }, { displayName: 'Flåede tomater' }, { displayName: 'Løg' }, { displayName: 'Hvidløg' }],
      },
      {
        candidateId: 'mock-4',
        recipeTemplateId: 'minced-pork-broccoli',
        recipeName: 'Hakket svinekød & Broccoli',
        servingsPerBatch: 3,
        basketCostDkk: 55,
        recipeCostDkk: 43,
        pricePerMealDkk: 14.3,
        storesUsed: [
          { storeId: 'netto', chainId: 'netto', storeName: 'Netto', distanceMeters: 650 },
          { storeId: 'lidl', chainId: 'lidl', storeName: 'Lidl', distanceMeters: 900 },
        ],
        interStoreDistanceMeters: 280,
        walkingDistanceMeters: 930,
        chosenIngredients: [
          { slotKey: 'meat', ingredientFamilyId: 'minced-pork', ingredientFamilyName: 'Hakket svinekød', requiredQuantity: { value: 300, unit: 'g' } },
          { slotKey: 'vegetable', ingredientFamilyId: 'broccoli', ingredientFamilyName: 'Broccoli', requiredQuantity: { value: 500, unit: 'g' } },
        ],
        basketLines: [
          {
            ingredientFamilyId: 'minced-pork', ingredientFamilyName: 'Hakket svinekød',
            productName: 'Hakket svinekød 8-12%', storeId: 'lidl', storeName: 'Lidl',
            packageQuantity: 500, packageUnit: 'g', packageBaseAmount: 500,
            requiredAmountForRecipe: 300, requiredAmountUnit: 'g',
            packagePriceDkk: 30, apportionedCostDkk: 18, leftoverAmount: 200, leftoverUnit: 'g',
          },
          {
            ingredientFamilyId: 'broccoli', ingredientFamilyName: 'Broccoli',
            productName: 'Broccoli buketter', storeId: 'netto', storeName: 'Netto',
            packageQuantity: 500, packageUnit: 'g', packageBaseAmount: 500,
            requiredAmountForRecipe: 500, requiredAmountUnit: 'g',
            packagePriceDkk: 25, apportionedCostDkk: 25, leftoverAmount: 0, leftoverUnit: 'g',
          },
        ],
        sauceType: 'asian',
        pantryItems: [{ displayName: 'Ris' }, { displayName: 'Soja' }, { displayName: 'Honning' }, { displayName: 'Ingefær' }],
      },
      {
        candidateId: 'mock-5',
        recipeTemplateId: 'minced-veal-pork-broccoli',
        recipeName: 'Hakket kalv/flæsk & Broccoli',
        servingsPerBatch: 3,
        basketCostDkk: 70,
        recipeCostDkk: 55,
        pricePerMealDkk: 18.3,
        storesUsed: [{ storeId: 'foetex', chainId: 'foetex', storeName: 'føtex', distanceMeters: 1200 }],
        interStoreDistanceMeters: null,
        walkingDistanceMeters: 1200,
        chosenIngredients: [
          { slotKey: 'meat', ingredientFamilyId: 'minced-veal-pork', ingredientFamilyName: 'Hakket kalv/flæsk', requiredQuantity: { value: 300, unit: 'g' } },
          { slotKey: 'vegetable', ingredientFamilyId: 'broccoli', ingredientFamilyName: 'Broccoli', requiredQuantity: { value: 500, unit: 'g' } },
        ],
        basketLines: [
          {
            ingredientFamilyId: 'minced-veal-pork', ingredientFamilyName: 'Hakket kalv/flæsk',
            productName: 'Hakket kalv og flæsk', storeId: 'foetex', storeName: 'føtex',
            packageQuantity: 400, packageUnit: 'g', packageBaseAmount: 400,
            requiredAmountForRecipe: 300, requiredAmountUnit: 'g',
            packagePriceDkk: 45, apportionedCostDkk: 33.75, leftoverAmount: 100, leftoverUnit: 'g',
          },
          {
            ingredientFamilyId: 'broccoli', ingredientFamilyName: 'Broccoli',
            productName: 'Broccoli (estimeret pris)', storeId: 'foetex', storeName: 'føtex',
            packageQuantity: 500, packageUnit: 'g', packageBaseAmount: 500,
            requiredAmountForRecipe: 500, requiredAmountUnit: 'g',
            packagePriceDkk: 25, apportionedCostDkk: 25, leftoverAmount: 0, leftoverUnit: 'g',
            estimated: true,
          },
        ],
        sauceType: 'cream',
        pantryItems: [{ displayName: 'Pasta' }, { displayName: 'Smør' }, { displayName: 'Hvidløg' }, { displayName: 'Fløde' }],
        hasEstimatedPrice: true,
      },
    ],
    summary: {
      generatedAt: new Date().toISOString(),
      totalCandidates: 5,
      totalStoresInScope: 4,
      totalStorePairsConsidered: 2,
    },
  };
}
